
services:
  grafana:
    image: grafana/grafana:9.3.0
    container_name: grafana
    ports:
      - "3001:3000"  # Access Grafana via http://localhost:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage: