apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  namespace: grafana-poc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/grafana-dashboards