apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  namespace: grafana-poc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: grafana-poc   # Name of the disk created in Step 1
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-poc-storage-class