apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboards-pvc
  namespace: grafana-poc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName:  grafana-dashboards-pv
  storageClassName: grafana-poc-storage-class