{
 "title": "Mongo Between",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "address", "query": { "query": "label_values(address)" } }
  ]
 },
 "panels": [
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Apps --> MongoBetween",
   "type": "stat",
   "description": "จำนวน connection ที่เปิดอยู่ในปัจจุบันระหว่าง App กับ Proxy",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongobetween_open_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection MongoBetween --> MongoDB",
   "type": "stat",
   "description": "จำนวน connection ที่เปิดอยู่ในปัจจุบันระหว่าง App กับ Proxy",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongobetween_pool_open_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Using MongoBetween --> MongoDB",
   "type": "stat",
   "description": "จำนวน connection ที่เปิดอยู่ในปัจจุบันระหว่าง App กับ Proxy",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongobetween_pool_checked_out_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "End-to-End Latency Apps <--> MongoDB",
   "type": "timeseries",
   "description": "เวลาทั้งหมดที่ตั้งแต่ส่ง request จาก application จนได้รับ response จาก mongodb",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms/req" } },
   "targets": [
    {
     "expr": "sum(rate(mongobetween_handle_message_sum[$__rate_interval])) by (instance) / sum(rate(mongobetween_handle_message_count[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Round Trip Latency MongoBetween <--> $address",
   "type": "timeseries",
   "description": "เวลาเฉลี่ยที่ใช้สื่อสารกับ MongoDB โดยไม่รวมเวลาใน Proxy",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "address",
   "fieldConfig": { "defaults": { "unit": "ms/req" } },
   "targets": [
    {
     "expr": "sum(rate(mongobetween_round_trip_sum{address=~\"$address\"}[$__rate_interval])) by (address) / sum(rate(mongobetween_round_trip_count{address=~\"$address\"}[$__rate_interval])) by (address)",
     "legendFormat": "{{address}}"
    }
   ]
  },
  { "title": "Proxy Internal State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Active Cursors",
   "type": "stat",
   "description": "จำนวน cursor ที่เปิดอยู่ใน Proxy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongobetween_cursors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "stat",
   "description": "จำนวน transaction ที่ยังเปิดอยู่",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongobetween_transactions", "legendFormat": "__auto" }
   ]
  }
 ]
}