{
 "title": "Qdrant",
 "time": { "from": "2025-07-19T16:07:14.175Z", "to": "2025-07-22T14:44:23.217Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "CPU Usage Percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Memory Usage Percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^.*qdrant.*\", node=~\"$instance\"}) by (node)\r\n/\r\nsum(kube_pod_container_resource_limits{namespace=~\"^.*qdrant.*\"}) by (node)\r\n* 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Usage Percentage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{instance=~\"$instance\"}) by (instance)\r\n/\r\nsum(kubelet_volume_stats_capacity_bytes{instance=~\"$instance\"}) by (instance)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}